Task that replaces subsequences.
Gorbachevaa/TAT_tasks pull request #8
Opened 2017-09-29 08:45 UTC by Gorbachevaa

2017-09-29 16:20 UTC, IgorKheidorov requested changes
Not bad, change class names to nouns and methods to verbs)

2017-09-29 16:20 UTC, IgorKheidorov commented on Dev-9/SymbolsReplacement.cs
> +        public void Outputer(char[] sequence)
Bad idea, convert to string and output string

2017-09-29 16:20 UTC, IgorKheidorov commented on Dev-9/SymbolsReplacement.cs
> +            for (int i = 0; i < randPosSecond; i++)
better to use method to copy one massive to another

2017-09-29 16:20 UTC, IgorKheidorov commented on Dev-9/FileChecker.cs
> +        private int amount;
Simplify public int Amount {get;set;}

2017-09-29 16:20 UTC, IgorKheidorov commented on Dev-9/SymbolsReplacement.cs
> +            for (int i = randPosSecond; i < randPosSecond + lengthSubseqFirst; i++)
Copy array to array, try to find appropriate method

2017-10-02 19:41 UTC, IgorKheidorov approved these changes

2017-10-02 19:41 UTC, IgorKheidorov commented on Dev-9/FileChecker.cs
> +    class FileChecker
bad class name

2017-10-02 19:41 UTC, IgorKheidorov commented on Dev-9/FileChecker.cs
> +                string temp = fs.ReadLine();
Bug!!! if file will contain more then two lines SequencesFromFile[i] = temp cause exception!!!!

2017-10-02 19:41 UTC, IgorKheidorov commented on Dev-9/FileChecker.cs
> +                string temp = fs.ReadLine();
"using" is necessary

2017-10-02 19:41 UTC, IgorKheidorov commented on Dev-9/SymbolsReplacer.cs
> +            for (int i = 0; i < lengthSubseq; i++)
use subsequence.Length

2017-10-02 22:32 UTC, Gorbachevaa commented on Dev-9/FileChecker.cs
> +                string temp = fs.ReadLine();
I have variable Amount  = 2 which means that there are two lines in file. To avoid exception I had to change Amount to 3 or more. Is it too bad?

2017-10-03 18:46 UTC, merged